
name: airports.json build
on:
  push:
  schedule:
    # schedule 1st of every month
    - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - name: Node LTS versions
      uses: msimerson/node-lts-versions@v1.1.1
      env:
        FORCE_COLOR: 0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        allow_empty_commit: true