
name: Update airports.json
on:
  push:
  schedule:
    # schedule 1st of every month
    - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make API Call
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://airlabs.co/api/v9/airports?api_key=${{secrets.API_KEY}}'
        method: 'GET'
        responseFile: airports.json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - name: Node LTS versions
      uses: msimerson/node-lts-versions@v1.1.1
      env:
        FORCE_COLOR: 0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present     
    - name: Commit files  # transfer the new html files back into the repository
      run: |
        git config --local user.name  ${{ github.actor }}
        git add -A
        git commit -m "Updating airports.json file" || echo "no new change"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true